FROM golang:1.22-alpine as builder
WORKDIR /build
COPY go.mod go.sum ./
RUN  go mod download
COPY db ./db
COPY consumer ./consumer

RUN go build -o consumer/main ./consumer/main.go
FROM alpine:3
COPY --from=builder /build/consumer/main /bin/main
COPY consumer/configs /configs
COPY .env ./
ENTRYPOINT ["/bin/main"]