version: '3.8'

services:
  db:
    container_name: postgres_container
    restart: always
    image: postgres:latest
    volumes:
      - ./storage/postgres/data:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=kafka_test
      - POSTGRES_PASSWORD=qwerty12
      - POSTGRES_USER=kafka_test
    user: root
    ports:
      - "5436:5432"
    networks:
      - db-network


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_container
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
        - kafka-network

  producer:
    container_name: producer_container
    build:
      context: .
      dockerfile: Dockerfile.producer
    ports:
      - "8081:8080"
    depends_on:
      - db
      - kafka
    volumes: # Add this section
      - .:/build  # Map the . directory to /build inside the container
    environment:
      - DB_PASSWORD=qwerty12
    networks:
        - kafka-network
        - db-network

  consumer:
    container_name: consumer_container
    build:
      context: .
      dockerfile: Dockerfile.consumer
    ports:
      - "8082:8080"
    depends_on:
        - db
        - kafka
    volumes:
      - .:/build
    environment:
        - DB_PASSWORD=qwerty12
    networks:
        - kafka-network
        - db-network

networks:
  kafka-network:
    driver: bridge
  db-network:
    driver: bridge